using Llama.csharp.Interfaces;
using Llama.csharp.Native;
using System.Runtime.CompilerServices;

namespace Llama.csharp
{
    /// <summary>
    /// The base class for custom LLama executors.
    /// </summary>
    public abstract class LlamaExecutorBase
    {
        /// <summary>
        /// The tokens that were already processed by the model.
        /// </summary>
        protected int _pastTokensCount; // n_past
        /// <summary>
        /// The tokens that were consumed by the model during the current inference.
        /// </summary>
        protected int _consumedTokensCount; // n_consume
        /// <summary>
        /// 
        /// </summary>
        protected int _n_session_consumed;
        /// <summary>
        /// 
        /// </summary>
        protected int _n_matching_session_tokens;
        /// <summary>
        /// The path of the session file.
        /// </summary>
        protected string? _pathSession;
        /// <summary>
        /// A container of the tokens to be processed and after processed.
        /// </summary>
        protected List<LLamaToken> _embeds = new(); // embd
        /// <summary>
        /// A container for the tokens of input.
        /// </summary>
        protected List<LLamaToken> _embed_inps = new();
        /// <summary>
        /// 
        /// </summary>
        protected List<LLamaToken> _session_tokens = new();
        /// <summary>
        /// The last tokens generated by the model.
        /// </summary>
        protected FixedSizeQueue<LLamaToken> _last_n_tokens;
        /// <summary>
        /// The context used by the executor.
        /// </summary>
        public LLamaContext Context { get; }

        /// <summary>
        /// Tracks anti-prompts across streamed output.
        /// </summary>
        protected AntipromptProcessor AntipromptProcessor { get; }

        ////////Добавить словарь, который хранит соотнощение - сообщение-позиции и метод для 
        ////////    удаления последенего да и ваще любого сообщения 
        ////////    (при удалении послденего надо сдвигать текущий _pastTokensCount на начало до сообщения которое удаляем
        ////////        , в других случаях удаления гдето в начале или середине не надо менять _pastTokensCount)
        ////////    внутри каждого элемента массива сообщений также хранится массив токенов с позициями, для замены какого то символа отдельного
        ////////    при замене, декодится только то что после токена

        //// LLava Section 
        ////
        ///// <inheritdoc />
        //public bool IsMultiModal
        //{
        //    get
        //    {
        //        return ClipModel != null;
        //    }
        //}

        ///// <inheritdoc />
        //public LLavaWeights? ClipModel { get; }

        ///// <inheritdoc />
        //public List<byte[]> Images { get; }

        private readonly StreamingTokenDecoder _decoder;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="context"></param>
        /// <param name="logger"></param>
        protected LlamaExecutorBase(LLamaContext context)//, ILogger? logger = null)
        {
            //Images = new List<byte[]>();
            //_logger = logger;
            Context = context;
            _pastTokensCount = 0;
            _consumedTokensCount = 0;
            _n_session_consumed = 0;
            _last_n_tokens = new FixedSizeQueue<LLamaToken>((int)Context.ContextSize);
            _decoder = new StreamingTokenDecoder(context);
            AntipromptProcessor = new AntipromptProcessor();
        }

        ///// <summary>
        ///// 
        ///// </summary>
        ///// <param name="context"></param>
        ///// <param name="lLavaWeights"></param>
        ///// <param name="logger"></param>
        //public LlamaExecutorBase(LLamaContext context, LLavaWeights lLavaWeights, ILogger? logger = null) :
        //                this(context, logger)
        //{
        //    ClipModel = lLavaWeights;
        //}


        /// <summary>
        /// After running out of the context, take some tokens from the original prompt and recompute the logits in batches.
        /// </summary>
        /// <param name="tokensToKeep"></param>
        protected virtual void HandleRunOutOfContext(int tokensToKeep)
        {
            //// if we run out of context:
            //// - take the tokensToKeep first tokens from the original prompt (via n_past)
            //// - take half of the last (n_ctx - tokensToKeep) tokens and recompute the logits in batches
            //int n_left = _pastTokensCount - tokensToKeep;
            //int n_discard = n_left / 2;

            //NativeApi.llama_kv_self_seq_rm(Context.NativeHandle, LLamaSeqId.Zero, tokensToKeep, tokensToKeep + n_discard);
            //NativeApi.llama_kv_self_seq_add(Context.NativeHandle, LLamaSeqId.Zero, tokensToKeep + n_discard, _pastTokensCount, -n_discard);

            //_pastTokensCount -= n_discard;
            //// stop saving session if we run out of context
            //_pathSession = string.Empty;
        }

        /// <summary>
        /// Preprocess the inputs before the inference.
        /// </summary>
        /// <param name="text"></param>
        protected abstract void PreprocessInputs(string? text, bool addBos, bool special);

        /// <summary>
        /// Process the inputs to context
        /// </summary>
        /// <param name="text"></param>
        protected abstract Task ProcessInputs(IInferenceParams inferenceParams);

        /// <summary>
        /// Do some post processing after the inference.
        /// </summary>
        /// <param name="inferenceParams"></param>
        /// <param name="args"></param>
        /// <returns></returns>
        protected abstract void PostProcess(IInferenceParams inferenceParams, InferStateArgs args);

        /// <summary>
        /// The core inference logic.
        /// </summary>
        /// <param name="inferenceParams"></param>
        /// <param name="args"></param>
        /// <param name="cancellationToken"></param>
        protected abstract Task InferenceInternal(IInferenceParams inferenceParams, InferStateArgs args);

        /// <summary>
        /// Get the current state data.
        /// </summary>
        /// <returns></returns>
        public abstract LlamaBaseState GetStateData();

        public async Task ProcessPrompt(string? text, IInferenceParams? inferenceParams = null, bool addBos = false, bool special = true)
        {
            inferenceParams ??= new InferenceParams();

            _embeds.Clear();

            PreprocessInputs(text, addBos, special);

            await ProcessInputs(inferenceParams);
        }

        public virtual async IAsyncEnumerable<string> Generate(IInferenceParams? inferenceParams = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
        {
            inferenceParams ??= new InferenceParams();

            var args = new InferStateArgs
            {
                Antiprompts = [.. inferenceParams.AntiPrompts],
                RemainedTokens = inferenceParams.MaxTokens,
                ReturnValue = false,
                StopGeneration = false,
                AutoStopFromEOG = inferenceParams.AutoStopFromEOG
                //NeedToSaveSession = !string.IsNullOrEmpty(_pathSession) && _n_matching_session_tokens < _embed_inps.Count
            };

            AntipromptProcessor.ClearString();
            AntipromptProcessor.SetAntiprompts(inferenceParams.AntiPrompts ?? []);

            _embeds.Clear();

            while (!args.StopGeneration)
            {
                if (cancellationToken.IsCancellationRequested)
                {
                    break;
                }

                args.LastOutput = string.Empty;
                await InferenceInternal(inferenceParams, args);

                if (args.ReturnValue)
                {
                    _decoder.DecodeSpecialTokens = inferenceParams.DecodeSpecialTokens;
                    _decoder.AddRange(_embeds);
                    var decoded = _decoder.Read();
                    args.LastOutput = decoded;
                    yield return decoded;
                }

                PostProcess(inferenceParams, args); //проверка антипромптов и конца, взвод WaitForInput

                _embeds.Clear();
            }
        }

        /// <summary>
        /// Execute the inference.
        /// </summary>
        /// <param name="text">The prompt. If null, generation will continue where it left off previously.</param>
        /// <param name="inferenceParams"></param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        public virtual async IAsyncEnumerable<string> InferAsync(string? text, IInferenceParams? inferenceParams = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
        {
            await ProcessPrompt(text, inferenceParams, false, true);

            await foreach (string token in Generate(inferenceParams, cancellationToken))
            {
                yield return token;
            }
        }

        /// <summary>
        /// State arguments that are used in single inference
        /// </summary>
        protected class InferStateArgs
        {
            /// <summary>
            /// 
            /// </summary>
            public IList<string>? Antiprompts { get; set; }
            /// <summary>
            /// Tokens count remained to be used. (n_remain)
            /// </summary>
            public int RemainedTokens { get; set; }
            /// <summary>
            /// 
            /// </summary>
            public bool ReturnValue { get; set; }
            /// <summary>
            /// 
            /// </summary>
            public bool StopGeneration { get; set; }
            /// <summary>
            /// 
            /// </summary>
            public bool AutoStopFromEOG { get; set; }

            /// <summary>
            /// Most recent decoded output from the model.
            /// </summary>
            public string LastOutput { get; set; } = string.Empty;
        }

        public class LlamaBaseState
        {
            public int PastTokensCount { get; set; }

            public int ConsumedTokensCount { get; set; }

            public int ConsumedSessionCount { get; set; }

            public int MatchingSessionTokensCount { get; set; }

            public string? SessionFilePath { get; set; }

            public LLamaToken[] Embeds { get; set; }

            public LLamaToken[] EmbedInps { get; set; }

            public LLamaToken[] SessionTokens { get; set; }

            public LLamaToken[] LastTokens { get; set; }

            public int LastTokensCapacity { get; set; }
        }

    }
}